### ISSUE TITLE
Could not find features file

### ISSUE THREAD

**Issue by linyv** [romeo14/Vehicle-Detection#3]
> Could not find features file
Traceback (most recent call last):
  File "E:\Vehicle-Detection-master\main.py", line 15, in <module>
    params, scaler = get_train_parameters()
  File "E:\Vehicle-Detection-master\train.py", line 99, in get_train_parameters
    raise
RuntimeError: No active exception to reraise

Is it supposed to have a file similar to model_SVC_16_16_9_8_2_ (0, 1, 2) _True_True_True.p? Thank you!

**Comment by karthickal** [comment]
Uncomment line 11 from main.py

```
clf, params, scaler = train_classifier()
```

This will train the model on the training images and create model and features file in your local directory.

**Comment by linyv** [comment]
OK! Thank you!

**Comment by linyv** [comment]
memory error
> Traceback (most recent call last):
  File "E:\Vehicle-Detection-master\main.py", line 11, in <module>
    clf, params, scaler = train_classifier()
  File "E:\Vehicle-Detection-master\train.py", line 225, in train_classifier
    X_train, y_train, X_test, y_test, scaler = load_features(sample_size)
  File "E:\Vehicle-Detection-master\train.py", line 168, in load_features
    X = np.vstack((car_features, non_car_features)).astype(np.float64)
  File "D:\Program Files\Python\Python36-32\lib\site-packages\numpy\core\shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "D:\Program Files\Python\Python36-32\lib\site-packages\numpy\core\shape_base.py", line 234, in <listcomp>
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "D:\Program Files\Python\Python36-32\lib\site-packages\numpy\core\shape_base.py", line 100, in atleast_2d
    ary = asanyarray(ary)
  File "D:\Program Files\Python\Python36-32\lib\site-packages\numpy\core\numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
MemoryError

**Comment by karthickal** [comment]
What is your hardware? Do you have GPU support?

**Comment by linyv** [comment]
PC

**Comment by linyv** [comment]
The computer's RAM is 4G and python's version is  3.6.0 (32 bit). Is it not appropriate for this algorithm?

**Comment by linyv** [comment]
OK! Compiled successfully!

**Comment by karthickal** [comment]
You can try removing some images from the training folders and try to run. I compiled this on a 2015 Macbook Pro.

**Comment by linyv** [comment]
How long does it take to run this program on a Macbook Pro?

**Comment by karthickal** [comment]
About 3 minutes for the entire set of images.

**Comment by karthickal** [comment]
Due to size restrictions and to keep the repository clean, the source code does not contain the extracted features file required to re-train the model. Please use the following code to train the model and create the necessary files in your local system - 

```
clf, params, scaler = train_classifier()
```

Make sure your hardware supports the required memory to train the classifier.
